package com.acme.core.enums;

public enum RoleType {
  DEVELOPER,
  ADMINISTRATOR,
  QUALITY_MANAGER,
  QUALITY_ASSURANCE,
  QUALITY_CONTROL,
  COMPLIANCE_MANAGER,
  DOCUMENT_CONTROLLER,
  PROCESS_OWNER,
  AUDITOR,
  INSPECTOR,
  REVIEWER,
  MANAGEMENT,
  BUMANAGER,
  MANAGER,
  OPERATION,
  SUPERVISOR,
  MAINTAINER,
  MEMBER;
}